using DNIMVC.Models.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace DNIMVC.Services.Database;

/// <summary>
///     The identity database context for this application.
///     Inherits from <see cref="IdentityDbContext{TUser,TRole,TKey}" /> which provides
///     all the built-in Identity table configurations for users, roles, claims, logins,
///     and tokens. Custom entity configurations are applied in <see cref="OnModelCreating" />.
/// </summary>
public class IdentityDataService(DbContextOptions<IdentityDataService> options)
    : IdentityDbContext<ApplicationUserModel, IdentityRole<Guid>, Guid>(options)
{
    /// <summary>
    ///     Configures the schema for all identity and application entities.
    ///     base.OnModelCreating must be called first to ensure Identity's own
    ///     configurations are applied before any customizations.
    /// </summary>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        ConfigureApplicationUserModel(modelBuilder);
        ConfigureRefreshTokenModel(modelBuilder);
    }

    /// <summary>
    ///     Overrides the default AspNet-prefixed table names generated by Identity
    ///     with cleaner, application-specific names. This is purely cosmetic but
    ///     keeps the database schema consistent and easier to read.
    /// </summary>
    private static void ConfigureApplicationUserModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApplicationUserModel>().ToTable("ApplicationUser");
        modelBuilder.Entity<IdentityRole<Guid>>().ToTable("ApplicationRole");
        modelBuilder.Entity<IdentityUserRole<Guid>>().ToTable("ApplicationUserRole");
        modelBuilder.Entity<IdentityUserClaim<Guid>>().ToTable("ApplicationUserClaim");
        modelBuilder.Entity<IdentityUserLogin<Guid>>().ToTable("ApplicationUserLogin");
        modelBuilder.Entity<IdentityUserToken<Guid>>().ToTable("ApplicationUserToken");
        modelBuilder.Entity<IdentityRoleClaim<Guid>>().ToTable("ApplicationRoleClaim");
    }

    /// <summary>
    ///     Configures the RefreshToken entity using the Fluent API.
    ///     Fluent API is preferred over data annotations as it keeps
    ///     configuration logic out of the model and provides more control
    ///     over the resulting schema.
    /// </summary>
    private static void ConfigureRefreshTokenModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RefreshTokenModel>(e =>
        {
            e.ToTable("RefreshToken");

            // Explicitly define the primary key and mark it as auto-generated.
            // EF Core convention would normally handle this, but is declared
            // explicitly here to avoid any ambiguity.
            e.HasKey(r => r.RefreshTokenId);
            e.Property(r => r.RefreshTokenId)
                .ValueGeneratedOnAdd();

            // A refresh token belongs to one user, and a user can have many
            // refresh tokens representing active sessions across multiple devices.
            // Cascading delete ensures tokens are cleaned up when a user is deleted.
            e.HasOne(r => r.ApplicationUser)
                .WithMany(u => u.RefreshTokens)
                .HasForeignKey(r => r.ApplicationUserId)
                .OnDelete(DeleteBehavior.Cascade);

            // Enforce uniqueness on the token string to prevent collisions
            // and allow efficient lookups during token validation.
            e.HasIndex(r => r.Token).IsUnique();
        });
    }
}